services:
  postgres:
    image: postgres:latest
    container_name: postgres-monorepo-template
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: "packages/api/.env"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - ./servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:
